#!/bin/bash
# bOS Session Start Hook
# Injects essential daily context into Claude's context at session start.
# Output goes to stdout → Claude sees it as injected context.

BOS_DIR="$(cd "$(dirname "$0")/../.." && pwd)"

echo "## bOS Session Context"
echo "Date: $(date '+%Y-%m-%d %H:%M %Z (%A)')"
echo ""

# ─── Crash Buffer Recovery (ISI-10) ───
# If .working.md exists, previous session crashed without /wrap-up
WORKING_FILE="$BOS_DIR/state/.working.md"
if [ -f "$WORKING_FILE" ]; then
  WORKING_AGE_HOURS=999
  WORKING_MTIME=$(stat -f '%m' "$WORKING_FILE" 2>/dev/null)
  if [ -n "$WORKING_MTIME" ]; then
    NOW_SEC_W=$(date "+%s")
    WORKING_AGE_HOURS=$(( (NOW_SEC_W - WORKING_MTIME) / 3600 ))
  fi
  if [ "$WORKING_AGE_HOURS" -le 48 ]; then
    echo "### ⚠️ CRASH RECOVERY — Previous session did not close cleanly"
    echo "Working state from crashed session:"
    cat "$WORKING_FILE"
    echo ""
    echo "**Process this first:** Review what was in progress and resume or discard."
    echo ""
  fi
  # Clean up after injection (session-end will recreate if needed)
  rm -f "$WORKING_FILE"
fi

# Top tasks (first 5 lines of tasks summary)
if [ -f "$BOS_DIR/state/tasks.md" ]; then
  echo "### Tasks"
  head -15 "$BOS_DIR/state/tasks.md" | grep -E '^\|.*\|$|^- ' | head -5
  echo ""
fi

# Active projects (critical for multi-project awareness)
if [ -f "$BOS_DIR/state/projects.md" ]; then
  echo "### Active Projects"
  # Dashboard table from projects.md (lines with | # | pattern)
  grep -E '^\| [0-9]+ \|' "$BOS_DIR/state/projects.md" | head -10
  echo ""
fi

# Buffer status (critical financial safety)
if [ -f "$BOS_DIR/state/finances.md" ]; then
  BUFFER=$(grep -i 'buffer' "$BOS_DIR/state/finances.md" | head -1)
  if [ -n "$BUFFER" ]; then
    echo "### Buffer: $BUFFER"
    echo ""
  fi
fi

# Critical context-bus signals
if [ -f "$BOS_DIR/state/context-bus.md" ]; then
  CRITICAL=$(grep -A2 'Priority: critical' "$BOS_DIR/state/context-bus.md" | grep -v '^--$' | head -6)
  if [ -n "$CRITICAL" ]; then
    echo "### Critical Signals"
    echo "$CRITICAL"
    echo ""
  fi
fi

# Telemetry summary (if exists)
if [ -f "$BOS_DIR/state/telemetry.md" ]; then
  echo "### Agent Performance"
  head -10 "$BOS_DIR/state/telemetry.md" | grep -E '^\|.*\|$|^Total|^Top|^Avg' | head -3
  echo ""
fi

# Pending evolution proposals
if [ -f "$BOS_DIR/state/evolution-proposals.md" ]; then
  PENDING=$(grep -c 'Status: pending' "$BOS_DIR/state/evolution-proposals.md" 2>/dev/null)
  if [ "$PENDING" -gt 0 ] 2>/dev/null; then
    echo "### Evolution: $PENDING pending proposals"
    echo ""
  fi
fi

# Handoff from previous session (generated by /wrap-up)
if [ -f "$BOS_DIR/state/handoff.md" ]; then
  HANDOFF_DATE=$(grep '<!-- Generated:' "$BOS_DIR/state/handoff.md" 2>/dev/null | grep -o '20[0-9][0-9]-[0-9][0-9]-[0-9][0-9]')
  if [ -n "$HANDOFF_DATE" ]; then
    # Check freshness (max 3 days)
    HANDOFF_SEC=$(date -j -f "%Y-%m-%d" "$HANDOFF_DATE" "+%s" 2>/dev/null)
    NOW_SEC_H=$(date "+%s")
    HANDOFF_AGE=$(( (NOW_SEC_H - HANDOFF_SEC) / 86400 ))
    if [ "$HANDOFF_AGE" -le 3 ]; then
      echo "### Session Handoff (from /wrap-up)"
      cat "$BOS_DIR/state/handoff.md" 2>/dev/null
      echo ""
    fi
  fi
fi

# Pre-morning brief (generated by /evening Night Cycle)
if [ -f "$BOS_DIR/state/.pre-morning.md" ]; then
  # Check if pre-morning is from today or yesterday (still relevant)
  PRE_MORNING_DATE=$(grep '^Date:' "$BOS_DIR/state/.pre-morning.md" 2>/dev/null | head -1 | sed 's/Date: //')
  TODAY=$(date '+%Y-%m-%d')
  if [ -n "$PRE_MORNING_DATE" ]; then
    echo "### Pre-Morning Brief (from /evening)"
    grep -E '^(Priority|Calendar|Pending|Energy|Suggested)' "$BOS_DIR/state/.pre-morning.md" 2>/dev/null
    echo ""
  fi
fi

# Yesterday's energy (for trend context)
if [ -f "$BOS_DIR/state/daily-log.md" ]; then
  LAST_ENTRY=$(grep "^|" "$BOS_DIR/state/daily-log.md" 2>/dev/null | tail -1)
  if [ -n "$LAST_ENTRY" ]; then
    echo "### Last Daily Log Entry"
    echo "$LAST_ENTRY"
    echo ""
  fi
fi

# ─── Recent Session Digests (cross-session continuity) ───
DIGEST_DIR="$BOS_DIR/state/.backup/session-digests"
if [ -d "$DIGEST_DIR" ]; then
  DIGEST_COUNT=$(ls -1 "$DIGEST_DIR"/*.md 2>/dev/null | wc -l | tr -d ' ')
  if [ "$DIGEST_COUNT" -gt 0 ] 2>/dev/null; then
    echo "### Recent Sessions ($DIGEST_COUNT total, showing last 3)"
    # Show topic line from last 3 digests
    for f in $(ls -t "$DIGEST_DIR"/*.md 2>/dev/null | head -3); do
      DIGEST_DATE=$(basename "$f" .md)
      DIGEST_TOPIC=$(grep -m1 '^## Topic:' "$f" 2>/dev/null | sed 's/^## Topic: //' | cut -c1-100)
      [ -z "$DIGEST_TOPIC" ] && DIGEST_TOPIC=$(grep -E -m1 '^## |^- ' "$f" 2>/dev/null | head -1 | cut -c1-100)
      echo "- $DIGEST_DATE: $DIGEST_TOPIC"
    done
    echo "Use /recall to search past sessions."
    echo ""
  fi
fi

# ─── Mobile App Sync ───
echo "### Mobile Sync"
echo "MANDATORY: Run /mobile-sync at session start. Read Supabase for data from bOS Mobile app."
echo "Tables: energy_log, mobile_tasks, expenses, notes, habits, habit_completions, water_log, sleep_log, weight_log"
echo ""

# ─── Data Gap Detection ───
# Checks for stale state files and injects DATA_GAP signals
TODAY=$(date '+%Y-%m-%d')
GAPS_FOUND=0

# daily-log: check last entry date
if [ -f "$BOS_DIR/state/daily-log.md" ]; then
  DAILY_LAST=$(grep "^| 20" "$BOS_DIR/state/daily-log.md" 2>/dev/null | head -1 | grep -o '20[0-9][0-9]-[0-9][0-9]-[0-9][0-9]' | head -1)
  if [ -n "$DAILY_LAST" ] && [ "$DAILY_LAST" != "$TODAY" ]; then
    # Calculate days since last entry (macOS)
    if date -j -f "%Y-%m-%d" "$DAILY_LAST" "+%s" >/dev/null 2>&1; then
      LAST_SEC=$(date -j -f "%Y-%m-%d" "$DAILY_LAST" "+%s")
      NOW_SEC=$(date "+%s")
      GAP_DAYS=$(( (NOW_SEC - LAST_SEC) / 86400 ))
      if [ "$GAP_DAYS" -gt 1 ]; then
        GAPS_FOUND=$((GAPS_FOUND + 1))
      fi
    fi
  fi
fi

# finances: check expenses this month
MONTH=$(date '+%Y-%m')
EXPENSE_THIS_MONTH=0
if [ -f "$BOS_DIR/state/finances.md" ]; then
  EXPENSE_THIS_MONTH=$(grep -c "^| $MONTH" "$BOS_DIR/state/finances.md" 2>/dev/null)
  EXPENSE_THIS_MONTH=${EXPENSE_THIS_MONTH:-0}
fi

# tasks: check Summary freshness
TASKS_STALE=0
if [ -f "$BOS_DIR/state/tasks.md" ]; then
  TASKS_DATE=$(grep -o '20[0-9][0-9]-[0-9][0-9]-[0-9][0-9]' "$BOS_DIR/state/tasks.md" 2>/dev/null | head -1)
  if [ -n "$TASKS_DATE" ] && [ "$TASKS_DATE" != "$TODAY" ]; then
    if date -j -f "%Y-%m-%d" "$TASKS_DATE" "+%s" >/dev/null 2>&1; then
      T_LAST=$(date -j -f "%Y-%m-%d" "$TASKS_DATE" "+%s")
      T_GAP=$(( ($(date "+%s") - T_LAST) / 86400 ))
      [ "$T_GAP" -gt 3 ] && TASKS_STALE=1
    fi
  fi
fi

# weekly-log: check if review done this week (Friday-Sunday only)
DOW=$(date '+%u')  # 1=Mon, 7=Sun
WEEKLY_GAP=0
if [ "$DOW" -ge 5 ] && [ -f "$BOS_DIR/state/weekly-log.md" ]; then
  # Check if current week has a completed review (non-empty Done column)
  THIS_WEEK_ENTRY=$(grep "^| $MONTH" "$BOS_DIR/state/weekly-log.md" 2>/dev/null | tail -1)
  if [ -z "$THIS_WEEK_ENTRY" ] || echo "$THIS_WEEK_ENTRY" | grep -q '| — |'; then
    WEEKLY_GAP=1
  fi
fi

# Output gaps
if [ "$GAPS_FOUND" -gt 0 ] || [ "$EXPENSE_THIS_MONTH" -eq 0 ] || [ "$TASKS_STALE" -eq 1 ] || [ "$WEEKLY_GAP" -eq 1 ]; then
  echo "### Data Gaps"
  [ "$GAPS_FOUND" -gt 0 ] && echo "DATA_GAP: daily-log | last: $DAILY_LAST | ${GAP_DAYS}d ago — ask about energy at natural moment"
  DAY_OF_MONTH=$(date '+%d' | sed 's/^0//')
  [ "$EXPENSE_THIS_MONTH" -eq 0 ] && [ "$DAY_OF_MONTH" -ge 5 ] && echo "DATA_GAP: finances | 0 expenses logged in $MONTH — remind about /log-expense or x [kwota] [kat]"
  [ "$TASKS_STALE" -eq 1 ] && echo "DATA_GAP: tasks | Summary outdated ${T_GAP}d — update Summary section"
  [ "$WEEKLY_GAP" -eq 1 ] && echo "DATA_GAP: weekly-log | no review this week — suggest /review-week"
  echo ""
fi

# ─── Proactive Check Signal ───
# Tells @boss to run proactive-check logic inline (nudges, overdue tasks, streak risks)
echo "### Proactive Check"
echo "PROACTIVE_CHECK: Run proactive-check logic NOW. Check: overdue tasks, habit streaks at risk, buffer alerts, follow-ups due. Surface TOP 2 nudges max. Do NOT announce the check — just act on findings."
echo ""
