#!/bin/bash
# bOS Tool Memory Logger (PostToolUse hook)
# Inspired by ReMe's Tool Memory — tracks MCP tool usage for learning.
# Logs: tool name, timestamp, success/failure to state/tool-log.md
# Goal: build data on which tools work, fail, are slow — informs agent decisions.

# Hook profiling: BOS_HOOK_PROFILE=minimal|standard|strict (default: standard)
# minimal = skip this hook entirely (saves ~50ms per tool call)
[ "${BOS_HOOK_PROFILE:-standard}" = "minimal" ] && exit 0

BOS_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
TOOL_LOG="$BOS_DIR/state/tool-log.md"
TOOL_LOG_JSONL="$BOS_DIR/state/tool-log.jsonl"
TIMESTAMP=$(date '+%Y-%m-%d %H:%M')
TODAY=$(date '+%Y-%m-%d')

# Read hook input from stdin (JSON with tool_name, tool_input, tool_output)
INPUT=$(cat)

# Extract tool name from hook input
TOOL_NAME=$(echo "$INPUT" | grep -o '"tool_name":"[^"]*"' | head -1 | sed 's/"tool_name":"//;s/"//')

# Skip if no tool name (shouldn't happen but safety)
if [ -z "$TOOL_NAME" ]; then
  echo "{\"ts\":\"$TIMESTAMP\",\"tool\":\"UNKNOWN\",\"status\":\"PARSE_FAIL\"}" >> "$TOOL_LOG_JSONL"
  exit 0
fi

# Log Skill invocations to skill-runs.jsonl
if [ "$TOOL_NAME" = "Skill" ]; then
  SKILL_NAME=$(echo "$INPUT" | grep -o '"skill":"[^"]*"' | head -1 | sed 's/"skill":"//;s/"//')
  if [ -n "$SKILL_NAME" ]; then
    SKILL_LOG="$BOS_DIR/state/skill-runs.jsonl"
    if echo "$INPUT" | grep -qi '"error"\|"Error"\|"failed"'; then
      echo "{\"ts\":\"$TIMESTAMP\",\"skill\":\"$SKILL_NAME\",\"result\":\"fail\",\"score\":0.3,\"notes\":\"auto-logged\"}" >> "$SKILL_LOG"
    else
      echo "{\"ts\":\"$TIMESTAMP\",\"skill\":\"$SKILL_NAME\",\"result\":\"success\",\"score\":0.8,\"notes\":\"auto-logged\"}" >> "$SKILL_LOG"
    fi
  fi
  exit 0
fi

# Skip non-MCP tools (Read, Write, Edit, Glob, Grep, Bash, Agent are internal)
case "$TOOL_NAME" in
  Read|Write|Edit|Glob|Grep|Bash|Agent|AskUserQuestion|ToolSearch|SendMessage|TaskCreate|TaskUpdate|TaskGet|TaskList|TaskStop|TaskOutput|NotebookEdit|ExitPlanMode|EnterPlanMode|EnterWorktree|ExitWorktree)
    exit 0
    ;;
esac

# FM-6: error detection from tool_response STATUS FIELD, not a grep of the whole input
TOOL_RESPONSE_BLOB=$(echo "$INPUT" | grep -o '"tool_response":.*' | head -c 2000)
if echo "$TOOL_RESPONSE_BLOB" | grep -qi '"is_error":\s*true\|"isError":\s*true'; then
  STATUS="FAIL"
elif [ -n "$TOOL_RESPONSE_BLOB" ] && echo "$TOOL_RESPONSE_BLOB" | grep -qi '"error":\|"status":"error"'; then
  STATUS="FAIL"
else
  STATUS="OK"
fi

# Create tool-log.md if doesn't exist
if [ ! -f "$TOOL_LOG" ]; then
  cat > "$TOOL_LOG" << 'EOF'
# Tool Memory Log
<!-- Auto-generated by PostToolUse hook. Tracks MCP tool usage for learning. -->
<!-- Inspired by ReMe Tool Memory (agentscope-ai/ReMe) -->

## Summary
| Metric | Value |
|--------|-------|
| Total calls | 0 |
| Unique tools | 0 |
| Fail rate | 0% |
| Last updated | — |

## Log
| Date | Tool | Status |
|------|------|--------|
EOF
fi

# Append log entry
echo "| $TIMESTAMP | $TOOL_NAME | $STATUS |" >> "$TOOL_LOG"

# Update summary (every 20 entries to avoid overhead)
LINE_COUNT=$(wc -l < "$TOOL_LOG" | tr -d ' ')
if [ $((LINE_COUNT % 20)) -eq 0 ]; then
  TOTAL=$(grep -c '^| 20' "$TOOL_LOG" 2>/dev/null || echo "0")
  FAILS=$(grep -c '| FAIL |' "$TOOL_LOG" 2>/dev/null || echo "0")
  UNIQUE=$(grep '^| 20' "$TOOL_LOG" 2>/dev/null | awk -F'|' '{gsub(/^ +| +$/,"",$3); print $3}' | sort -u | wc -l | tr -d ' ')
  if [ "$TOTAL" -gt 0 ]; then
    FAIL_RATE=$(( (FAILS * 100) / TOTAL ))
  else
    FAIL_RATE=0
  fi

  # Update summary in-place (macOS compatible)
  if [[ "$OSTYPE" == "darwin"* ]]; then
    sed -i '' "s/| Total calls | .*/| Total calls | $TOTAL |/" "$TOOL_LOG"
    sed -i '' "s/| Unique tools | .*/| Unique tools | $UNIQUE |/" "$TOOL_LOG"
    sed -i '' "s/| Fail rate | .*/| Fail rate | ${FAIL_RATE}% |/" "$TOOL_LOG"
    sed -i '' "s/| Last updated | .*/| Last updated | $TIMESTAMP |/" "$TOOL_LOG"
  else
    sed -i "s/| Total calls | .*/| Total calls | $TOTAL |/" "$TOOL_LOG"
    sed -i "s/| Unique tools | .*/| Unique tools | $UNIQUE |/" "$TOOL_LOG"
    sed -i "s/| Fail rate | .*/| Fail rate | ${FAIL_RATE}% |/" "$TOOL_LOG"
    sed -i "s/| Last updated | .*/| Last updated | $TIMESTAMP |/" "$TOOL_LOG"
  fi
fi

exit 0
