#!/bin/bash
# Roster from disk. No Python. Deterministic --write.
# Usage: bash scripts/bos-roster.sh [--write]
set -eu
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WRITE=0
[ "${1:-}" = "--write" ] && WRITE=1
DRIFT=0
CAP=8192
SKILLS="$ROOT/.claude/skills"
AGENTS="$ROOT/.claude/agents"
HOOKS="$ROOT/.claude/hooks"
SETTINGS="$ROOT/.claude/settings.json"
OUT="$ROOT/config/roster.md"

# No mktemp — works in read-only Codex sandboxes. --write uses config/roster.md.new then mv.

echo "# bOS roster (disk)"
echo "VERSION $(cat "$ROOT/VERSION" 2>/dev/null || echo unknown)"
echo ""
echo "## Skills"
printf '%-18s %-8s %8s %6s %s\n' name tier bytes '8KB' refs
over=0
count=0
core_n=0
opt_n=0
for d in "$SKILLS"/*/; do
  [ -d "$d" ] || continue
  name=$(basename "$d")
  sm="$d/SKILL.md"
  if [ ! -f "$sm" ]; then
    echo "DRIFT: missing SKILL.md in $name" >&2
    DRIFT=1
    continue
  fi
  # First YAML block only. awk: n=1 between the two --- fences.
  tier=$(awk 'BEGIN{n=0} /^---[[:space:]]*$/{n++; next} n==1 && $1=="tier:"{print $2; exit}' "$sm")
  if [ "$tier" != "core" ] && [ "$tier" != "optional" ]; then
    echo "DRIFT: $name missing or invalid tier (want core|optional, got '${tier:-empty}')" >&2
    DRIFT=1
    tier="${tier:-?}"
  fi
  [ "$tier" = "core" ] && core_n=$((core_n + 1))
  [ "$tier" = "optional" ] && opt_n=$((opt_n + 1))
  bytes=$(wc -c < "$sm" | tr -d ' ')
  flag=ok
  if [ "$bytes" -gt "$CAP" ]; then
    flag=OVER
    over=$((over + 1))
  fi
  refs=no
  [ -d "$d/references" ] && refs=yes
  printf '%-18s %-8s %8s %6s %s\n' "$name" "$tier" "$bytes" "$flag" "$refs"
  count=$((count + 1))
  link="$ROOT/.agents/skills/$name"
  if [ ! -L "$link" ]; then
    echo "DRIFT: .agents/skills/$name is not a symlink" >&2
    DRIFT=1
  fi
done
echo "count=$count core=$core_n optional=$opt_n over_8kb=$over"
echo ""

echo "## Agents"
acount=0
for f in "$AGENTS"/*.md; do
  [ -f "$f" ] || continue
  n=$(basename "$f" .md)
  b=$(wc -c < "$f" | tr -d ' ')
  printf '%-18s %8s\n' "$n" "$b"
  acount=$((acount + 1))
done
echo "count=$acount"
if [ "$acount" -ne 10 ]; then
  echo "DRIFT: expected 10 agent files, got $acount" >&2
  DRIFT=1
fi
echo ""

echo "## Hooks"
# Wired commands from settings.json (paths after hooks/)
wired=$(grep -o 'bash [^"]*hooks/[^"]*' "$SETTINGS" || true)
wired_n=0
while IFS= read -r line; do
  [ -z "$line" ] && continue
  script=${line##*/}
  wired_n=$((wired_n + 1))
  if [ ! -f "$HOOKS/$script" ]; then
    echo "DRIFT: wired hook missing: $script" >&2
    DRIFT=1
  else
    echo "  wired  $script"
  fi
done <<EOF
$wired
EOF

echo "  helper ping-inject.sh (sourced, not in settings)"
[ -f "$HOOKS/ping-inject.sh" ] || { echo "DRIFT: ping-inject.sh missing" >&2; DRIFT=1; }

for p in "$HOOKS"/*.sh; do
  bn=$(basename "$p")
  [ "$bn" = "ping-inject.sh" ] && continue
  echo "$wired" | grep -q "$bn" && continue
  echo "DRIFT: extra hook in .claude/hooks: $bn (optional crons belong in examples/hooks/ntfy/)" >&2
  DRIFT=1
done

for banned in vault schedule; do
  if [ -d "$SKILLS/$banned" ]; then
    echo "DRIFT: $banned still in Lite" >&2
    DRIFT=1
  fi
done

[ -f "$ROOT/scripts/context-bus-append.sh" ] || { echo "DRIFT: scripts/context-bus-append.sh missing" >&2; DRIFT=1; }

echo ""
if [ "$WRITE" -eq 1 ]; then
  mkdir -p "$ROOT/config"
  {
    echo "# Generated by scripts/bos-roster.sh — do not hand-edit"
    echo "VERSION $(cat "$ROOT/VERSION")"
    echo ""
    echo "## Skills"
    echo "| name | tier | bytes | 8KB | refs |"
    echo "|------|:----:|------:|:---:|:----:|"
    for d in "$SKILLS"/*/; do
      [ -d "$d" ] || continue
      name=$(basename "$d")
      sm="$d/SKILL.md"
      [ -f "$sm" ] || continue
      tier=$(awk 'BEGIN{n=0} /^---[[:space:]]*$/{n++; next} n==1 && $1=="tier:"{print $2; exit}' "$sm")
      [ -n "$tier" ] || tier="?"
      bytes=$(wc -c < "$sm" | tr -d ' ')
      flag=ok
      [ "$bytes" -gt "$CAP" ] && flag=OVER
      refs=no
      [ -d "$d/references" ] && refs=yes
      printf '| %s | %s | %s | %s | %s |\n' "$name" "$tier" "$bytes" "$flag" "$refs"
    done
    echo ""
    echo "count $count · core $core_n · optional $opt_n · over_8kb $over"
    echo ""
    echo "## Agents"
    echo "| name | bytes |"
    echo "|------|------:|"
    for f in "$AGENTS"/*.md; do
      [ -f "$f" ] || continue
      printf '| %s | %s |\n' "$(basename "$f" .md)" "$(wc -c < "$f" | tr -d ' ')"
    done
    echo ""
    echo "## Hooks"
    echo "Wired in .claude/settings.json (6) + sourced ping-inject.sh."
    echo "Optional ntfy: examples/hooks/ntfy/"
  } > "$OUT"
  echo "Wrote $OUT"
fi

if [ "$DRIFT" -ne 0 ]; then
  echo "ROSTER DRIFT"
  exit 1
fi
echo "ROSTER OK"
exit 0
